# Write your query or mutation here
query Tastings {
  tastings: allTasting {
    edges {
      node {
        id
        date
        author {
          name
          image
        }
        tea_name
        rating
        genre {
          name
          category {
            name
          }
        }
        cultivar {
          name
        }
        season
        production_year
        origin {
          location
          municipality
          country
        }
        elevation
        images {
          image
          alt
        }
        brewing {
          temperature
          material_amount
          vessel
          liquid_amount
          first_infusion_duration
          infusion_increment
        }
        flavor_axes {
          vegetal {
            start
            finish
          }
          floral {
            start
            finish
          }
          fruits {
            start
            finish
          }
          spices {
            start
            finish
          }
          earth {
            start
            finish
          }
          wood {
            start
            finish
          }
          nuts_roast {
            start
            finish
          }
          cream {
            start
            finish
          }
          stone {
            start
            finish
          }
          umami {
            start
            finish
          }
        }
        notes {
          dry_leaf_nose
          wet_leaf_nose
          mouthfeel
          taste
          finish
          empty_cup
          cha_qi
        }
        content
      }
    }
  }
}
