query Tastings {
  tastings: allTasting() {
    edges {
      node {
        id
        date
        tea_name
        season
        production_year
        genre {
          id
          parent
          name
        }
        images {
          image
          alt
        }
        brewing {
          temperature
          material_amount
          vessel
          liquid_amount
          first_infusion_duration
          infusion_increment
        }
      }
    }
  }
}
